import mongoose, {Schema} from "mongoose";
import jwt from "jsonwebtoken"
import bcrypt from "bcrypt"
    

const userSchema = new Schema(
    {
        username: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
            index: true
        },
        email: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
        },
        fullname: {
            type: String,
            required: true,
            trim: true,
            index: true,
        },
        avatar: {
            type: String,// cloudinary url
            required: true, 
        },
        coverImage: {
            type: String,// cloudinary url
        },
        watchHistory: [
            {
                type: Schema.Types.ObjectId,
                ref: "Video"
            }
        ],
        password:{
            type: String,
            required: [true, 'Password is required'],
        },
        refreshToken:{
            type: String,

        }
    },{timestamps: true}
)


userSchema.pre("save", async function (next) {
    if(this.isModified("password")){
        this.password = await bcrypt.hash(this.password, 10)
    }
    next()//it basically tells mongoose that i am done with the pre operation , so continue the save operation 
})

userSchema.methods.isPasswordCorrect = async function(password){
  return await bcrypt.compare(password, this.password)
}
//passwrod --> entered by user 
// this.password --> already stored in DB (hashed value)


//Note -> Header is not explicitly written it is generated by the jwt library 
// header mainly contains two things --> algorithm , token type = jwt 
userSchema.methods.generateAccessToken = function(){
   return jwt.sign(
    //this is palyload --> contains some claims/data about user 
        {
            _id: this._id,
            email: this.email,
            username: this.username,
            fullname: this.fullname
        },
        //this is secret it's used to create or verify the signature    
        process.env.ACCESS_TOKEN_SECRET,

        //this is neither payloar nor signature it's an option passed to  jwt.sign() --> tells expiration time 
        {
            expiresIn: process.env.ACCESS_TOKEN_EXPIRY
        }
    )
}

// refresh token --> used to get a new access token when the old ones expires
// stored more securely and secretly 
userSchema.methods.generateRefreshToken = function(){
    return jwt.sign(
        {
            _id: this._id,
        },
        process.env.REFRESH_TOKEN_SECRET,
        {
            expiresIn: process.env.REFRESH_TOKEN_EXPIRY
        }
    )
}


export const User = mongoose.model("User", userSchema)